### ISSUE TITLE
cast.ToInt bugs on zero padding string

### ISSUE THREAD

**Issue by changwuf31** [spf13/cast#56]
on "04", parsed to 4,
but on "08", parsed to 0

using go 1.7

**Comment by moorereason** [comment]
`ToInt` uses `strconv.ParseInt(s, 0, 0)` behind the scenes with the second argument representing the "base."  From the [strconv godocs](https://golang.org/pkg/strconv/#ParseInt):

> If base == 0, the base is implied by the string's prefix: base 16 for "0x", base 8 for "0", and base 10 otherwise.

"08" is an invalid base 8 string.

I would recommend trimming the zero padding off before sending to `ToIntE`.  Also, I would recommend using `ToIntE` so that you know when are error is returned, which would be the case here.

**Comment by changwuf31** [comment]
Ah, you're right. Thank you
